// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/bank/service.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_bank_service_proto protoreflect.FileDescriptor

const file_proto_bank_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/bank/service.proto\x12\x04bank\x1a\x1dproto/bank/type/account.proto\x1a\x1eproto/bank/type/exchange.proto2\xac\x01\n" +
	"\vBankService\x12N\n" +
	"\x11GetCurrentBalance\x12\x1b.bank.CurrentBalanceRequest\x1a\x1c.bank.CurrentBalanceResponse\x12M\n" +
	"\x12FetchExchangeRates\x12\x19.bank.ExchangeRateRequest\x1a\x1a.bank.ExchangeRateResponse0\x01B5Z3github.com/sisco-exp/my-grpc-proto/protogen/go/bankb\x06proto3"

var file_proto_bank_service_proto_goTypes = []any{
	(*CurrentBalanceRequest)(nil),  // 0: bank.CurrentBalanceRequest
	(*ExchangeRateRequest)(nil),    // 1: bank.ExchangeRateRequest
	(*CurrentBalanceResponse)(nil), // 2: bank.CurrentBalanceResponse
	(*ExchangeRateResponse)(nil),   // 3: bank.ExchangeRateResponse
}
var file_proto_bank_service_proto_depIdxs = []int32{
	0, // 0: bank.BankService.GetCurrentBalance:input_type -> bank.CurrentBalanceRequest
	1, // 1: bank.BankService.FetchExchangeRates:input_type -> bank.ExchangeRateRequest
	2, // 2: bank.BankService.GetCurrentBalance:output_type -> bank.CurrentBalanceResponse
	3, // 3: bank.BankService.FetchExchangeRates:output_type -> bank.ExchangeRateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_service_proto_init() }
func file_proto_bank_service_proto_init() {
	if File_proto_bank_service_proto != nil {
		return
	}
	file_proto_bank_type_account_proto_init()
	file_proto_bank_type_exchange_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_service_proto_rawDesc), len(file_proto_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bank_service_proto_goTypes,
		DependencyIndexes: file_proto_bank_service_proto_depIdxs,
	}.Build()
	File_proto_bank_service_proto = out.File
	file_proto_bank_service_proto_goTypes = nil
	file_proto_bank_service_proto_depIdxs = nil
}
