// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/bank/service.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_bank_service_proto protoreflect.FileDescriptor

const file_proto_bank_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/bank/service.proto\x12\x04bank\x1a\x1dproto/bank/type/account.proto\x1a\x1eproto/bank/type/exchange.proto\x1a!proto/bank/type/transaction.proto\x1a\x1eproto/bank/type/transfer.proto2\xc3\x02\n" +
	"\vBankService\x12P\n" +
	"\x11GetCurrentBalance\x12\x1b.bank.CurrentBalanceRequest\x1a\x1c.bank.CurrentBalanceResponse\"\x00\x12O\n" +
	"\x12FetchExchangeRates\x12\x19.bank.ExchangeRateRequest\x1a\x1a.bank.ExchangeRateResponse\"\x000\x01\x12H\n" +
	"\x15SummarizeTransactions\x12\x11.bank.Transaction\x1a\x18.bank.TransactionSummary\"\x00(\x01\x12G\n" +
	"\x10TransferMultiple\x12\x15.bank.TransferRequest\x1a\x16.bank.TransferResponse\"\x00(\x010\x01B5Z3github.com/sisco-exp/my-grpc-proto/protogen/go/bankb\x06proto3"

var file_proto_bank_service_proto_goTypes = []any{
	(*CurrentBalanceRequest)(nil),  // 0: bank.CurrentBalanceRequest
	(*ExchangeRateRequest)(nil),    // 1: bank.ExchangeRateRequest
	(*Transaction)(nil),            // 2: bank.Transaction
	(*TransferRequest)(nil),        // 3: bank.TransferRequest
	(*CurrentBalanceResponse)(nil), // 4: bank.CurrentBalanceResponse
	(*ExchangeRateResponse)(nil),   // 5: bank.ExchangeRateResponse
	(*TransactionSummary)(nil),     // 6: bank.TransactionSummary
	(*TransferResponse)(nil),       // 7: bank.TransferResponse
}
var file_proto_bank_service_proto_depIdxs = []int32{
	0, // 0: bank.BankService.GetCurrentBalance:input_type -> bank.CurrentBalanceRequest
	1, // 1: bank.BankService.FetchExchangeRates:input_type -> bank.ExchangeRateRequest
	2, // 2: bank.BankService.SummarizeTransactions:input_type -> bank.Transaction
	3, // 3: bank.BankService.TransferMultiple:input_type -> bank.TransferRequest
	4, // 4: bank.BankService.GetCurrentBalance:output_type -> bank.CurrentBalanceResponse
	5, // 5: bank.BankService.FetchExchangeRates:output_type -> bank.ExchangeRateResponse
	6, // 6: bank.BankService.SummarizeTransactions:output_type -> bank.TransactionSummary
	7, // 7: bank.BankService.TransferMultiple:output_type -> bank.TransferResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_service_proto_init() }
func file_proto_bank_service_proto_init() {
	if File_proto_bank_service_proto != nil {
		return
	}
	file_proto_bank_type_account_proto_init()
	file_proto_bank_type_exchange_proto_init()
	file_proto_bank_type_transaction_proto_init()
	file_proto_bank_type_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_service_proto_rawDesc), len(file_proto_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bank_service_proto_goTypes,
		DependencyIndexes: file_proto_bank_service_proto_depIdxs,
	}.Build()
	File_proto_bank_service_proto = out.File
	file_proto_bank_service_proto_goTypes = nil
	file_proto_bank_service_proto_depIdxs = nil
}
