// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/bank/type/transaction.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_IN          TransactionType = 1
	TransactionType_TRANSACTION_TYPE_OUT         TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_IN",
		2: "TRANSACTION_TYPE_OUT",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_IN":          1,
		"TRANSACTION_TYPE_OUT":         2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_type_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_bank_type_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	Type          TransactionType        `protobuf:"varint,2,opt,name=type,proto3,enum=bank.TransactionType" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     *datetime.DateTime     `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTimestamp() *datetime.DateTime {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type TransactionSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber   string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	SumAmountIn     float64                `protobuf:"fixed64,2,opt,name=sum_amount_in,proto3" json:"sum_amount_in,omitempty"`
	SumAmountOut    float64                `protobuf:"fixed64,3,opt,name=sum_amount_out,proto3" json:"sum_amount_out,omitempty"`
	SumTotal        float64                `protobuf:"fixed64,4,opt,name=sum_total,json=sumTotal,proto3" json:"sum_total,omitempty"`
	TransactionDate *date.Date             `protobuf:"bytes,5,opt,name=transaction_date,proto3" json:"transaction_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSummary) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionSummary) GetSumAmountIn() float64 {
	if x != nil {
		return x.SumAmountIn
	}
	return 0
}

func (x *TransactionSummary) GetSumAmountOut() float64 {
	if x != nil {
		return x.SumAmountOut
	}
	return 0
}

func (x *TransactionSummary) GetSumTotal() float64 {
	if x != nil {
		return x.SumTotal
	}
	return 0
}

func (x *TransactionSummary) GetTransactionDate() *date.Date {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

var File_proto_bank_type_transaction_proto protoreflect.FileDescriptor

const file_proto_bank_type_transaction_proto_rawDesc = "" +
	"\n" +
	"!proto/bank/type/transaction.proto\x12\x04bank\x1a\x1cproto/google/type/date.proto\x1a proto/google/type/datetime.proto\"\xc3\x01\n" +
	"\vTransaction\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.bank.TransactionTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x123\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x15.google.type.DateTimeR\ttimestamp\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xe6\x01\n" +
	"\x12TransactionSummary\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12$\n" +
	"\rsum_amount_in\x18\x02 \x01(\x01R\rsum_amount_in\x12&\n" +
	"\x0esum_amount_out\x18\x03 \x01(\x01R\x0esum_amount_out\x12\x1b\n" +
	"\tsum_total\x18\x04 \x01(\x01R\bsumTotal\x12=\n" +
	"\x10transaction_date\x18\x05 \x01(\v2\x11.google.type.DateR\x10transaction_date*f\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRANSACTION_TYPE_IN\x10\x01\x12\x18\n" +
	"\x14TRANSACTION_TYPE_OUT\x10\x02B5Z3github.com/sisco-exp/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_transaction_proto_rawDescOnce sync.Once
	file_proto_bank_type_transaction_proto_rawDescData []byte
)

func file_proto_bank_type_transaction_proto_rawDescGZIP() []byte {
	file_proto_bank_type_transaction_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)))
	})
	return file_proto_bank_type_transaction_proto_rawDescData
}

var file_proto_bank_type_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bank_type_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_transaction_proto_goTypes = []any{
	(TransactionType)(0),       // 0: bank.TransactionType
	(*Transaction)(nil),        // 1: bank.Transaction
	(*TransactionSummary)(nil), // 2: bank.TransactionSummary
	(*datetime.DateTime)(nil),  // 3: google.type.DateTime
	(*date.Date)(nil),          // 4: google.type.Date
}
var file_proto_bank_type_transaction_proto_depIdxs = []int32{
	0, // 0: bank.Transaction.type:type_name -> bank.TransactionType
	3, // 1: bank.Transaction.timestamp:type_name -> google.type.DateTime
	4, // 2: bank.TransactionSummary.transaction_date:type_name -> google.type.Date
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bank_type_transaction_proto_init() }
func file_proto_bank_type_transaction_proto_init() {
	if File_proto_bank_type_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_transaction_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_transaction_proto_depIdxs,
		EnumInfos:         file_proto_bank_type_transaction_proto_enumTypes,
		MessageInfos:      file_proto_bank_type_transaction_proto_msgTypes,
	}.Build()
	File_proto_bank_type_transaction_proto = out.File
	file_proto_bank_type_transaction_proto_goTypes = nil
	file_proto_bank_type_transaction_proto_depIdxs = nil
}
