// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/bank/type/transfer.proto

package bank

import (
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferStatus int32

const (
	TransferStatus_TRANSFER_STATUS_UNSPECIFIED TransferStatus = 0
	TransferStatus_TRANSFER_STATUS_SUCCESS     TransferStatus = 1
	TransferStatus_TRANSFER_STATUS_FAILED      TransferStatus = 2
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TRANSFER_STATUS_UNSPECIFIED",
		1: "TRANSFER_STATUS_SUCCESS",
		2: "TRANSFER_STATUS_FAILED",
	}
	TransferStatus_value = map[string]int32{
		"TRANSFER_STATUS_UNSPECIFIED": 0,
		"TRANSFER_STATUS_SUCCESS":     1,
		"TRANSFER_STATUS_FAILED":      2,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_type_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_proto_bank_type_transfer_proto_enumTypes[0]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{0}
}

type TransferRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromAccountNumber string                 `protobuf:"bytes,1,opt,name=from_account_number,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,2,opt,name=to_account_number,proto3" json:"to_account_number,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount            float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_bank_type_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *TransferRequest) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromAccountNumber string                 `protobuf:"bytes,1,opt,name=from_account_number,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,2,opt,name=to_account_number,proto3" json:"to_account_number,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount            float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status            TransferStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=bank.TransferStatus" json:"status,omitempty"`
	Timestamp         *datetime.DateTime     `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_bank_type_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *TransferResponse) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *TransferResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *TransferResponse) GetTimestamp() *datetime.DateTime {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_bank_type_transfer_proto protoreflect.FileDescriptor

const file_proto_bank_type_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/bank/type/transfer.proto\x12\x04bank\x1a proto/google/type/datetime.proto\"\xa5\x01\n" +
	"\x0fTransferRequest\x120\n" +
	"\x13from_account_number\x18\x01 \x01(\tR\x13from_account_number\x12,\n" +
	"\x11to_account_number\x18\x02 \x01(\tR\x11to_account_number\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\x89\x02\n" +
	"\x10TransferResponse\x120\n" +
	"\x13from_account_number\x18\x01 \x01(\tR\x13from_account_number\x12,\n" +
	"\x11to_account_number\x18\x02 \x01(\tR\x11to_account_number\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.bank.TransferStatusR\x06status\x123\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x15.google.type.DateTimeR\ttimestamp*j\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\x1bTRANSFER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSFER_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_STATUS_FAILED\x10\x02B5Z3github.com/sisco-exp/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_transfer_proto_rawDescOnce sync.Once
	file_proto_bank_type_transfer_proto_rawDescData []byte
)

func file_proto_bank_type_transfer_proto_rawDescGZIP() []byte {
	file_proto_bank_type_transfer_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_transfer_proto_rawDesc), len(file_proto_bank_type_transfer_proto_rawDesc)))
	})
	return file_proto_bank_type_transfer_proto_rawDescData
}

var file_proto_bank_type_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bank_type_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_transfer_proto_goTypes = []any{
	(TransferStatus)(0),       // 0: bank.TransferStatus
	(*TransferRequest)(nil),   // 1: bank.TransferRequest
	(*TransferResponse)(nil),  // 2: bank.TransferResponse
	(*datetime.DateTime)(nil), // 3: google.type.DateTime
}
var file_proto_bank_type_transfer_proto_depIdxs = []int32{
	0, // 0: bank.TransferResponse.status:type_name -> bank.TransferStatus
	3, // 1: bank.TransferResponse.timestamp:type_name -> google.type.DateTime
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bank_type_transfer_proto_init() }
func file_proto_bank_type_transfer_proto_init() {
	if File_proto_bank_type_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_transfer_proto_rawDesc), len(file_proto_bank_type_transfer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_transfer_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_transfer_proto_depIdxs,
		EnumInfos:         file_proto_bank_type_transfer_proto_enumTypes,
		MessageInfos:      file_proto_bank_type_transfer_proto_msgTypes,
	}.Build()
	File_proto_bank_type_transfer_proto = out.File
	file_proto_bank_type_transfer_proto_goTypes = nil
	file_proto_bank_type_transfer_proto_depIdxs = nil
}
