// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/resiliency/resiliency.proto

package resiliency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResiliencyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MinDelaySeconds int32                  `protobuf:"varint,1,opt,name=min_delay_seconds,proto3" json:"min_delay_seconds,omitempty"`
	MaxDelaySeconds int32                  `protobuf:"varint,2,opt,name=max_delay_seconds,proto3" json:"max_delay_seconds,omitempty"`
	StatusCodes     []uint32               `protobuf:"varint,3,rep,packed,name=status_codes,proto3" json:"status_codes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResiliencyRequest) Reset() {
	*x = ResiliencyRequest{}
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyRequest) ProtoMessage() {}

func (x *ResiliencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyRequest.ProtoReflect.Descriptor instead.
func (*ResiliencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_resiliency_resiliency_proto_rawDescGZIP(), []int{0}
}

func (x *ResiliencyRequest) GetMinDelaySeconds() int32 {
	if x != nil {
		return x.MinDelaySeconds
	}
	return 0
}

func (x *ResiliencyRequest) GetMaxDelaySeconds() int32 {
	if x != nil {
		return x.MaxDelaySeconds
	}
	return 0
}

func (x *ResiliencyRequest) GetStatusCodes() []uint32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type ResiliencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DummyString   string                 `protobuf:"bytes,1,opt,name=dummy_string,proto3" json:"dummy_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResiliencyResponse) Reset() {
	*x = ResiliencyResponse{}
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyResponse) ProtoMessage() {}

func (x *ResiliencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyResponse.ProtoReflect.Descriptor instead.
func (*ResiliencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_resiliency_resiliency_proto_rawDescGZIP(), []int{1}
}

func (x *ResiliencyResponse) GetDummyString() string {
	if x != nil {
		return x.DummyString
	}
	return ""
}

var File_proto_resiliency_resiliency_proto protoreflect.FileDescriptor

const file_proto_resiliency_resiliency_proto_rawDesc = "" +
	"\n" +
	"!proto/resiliency/resiliency.proto\x12\n" +
	"resiliency\"\x93\x01\n" +
	"\x11ResiliencyRequest\x12,\n" +
	"\x11min_delay_seconds\x18\x01 \x01(\x05R\x11min_delay_seconds\x12,\n" +
	"\x11max_delay_seconds\x18\x02 \x01(\x05R\x11max_delay_seconds\x12\"\n" +
	"\fstatus_codes\x18\x03 \x03(\rR\fstatus_codes\"8\n" +
	"\x12ResiliencyResponse\x12\"\n" +
	"\fdummy_string\x18\x01 \x01(\tR\fdummy_string2\x90\x03\n" +
	"\x11ResiliencyService\x12R\n" +
	"\x0fUnaryResiliency\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00\x12^\n" +
	"\x19ServerStreamingResiliency\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x000\x01\x12^\n" +
	"\x19ClientStreamingResiliency\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00(\x01\x12g\n" +
	" BiDirectionalStreamingResiliency\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00(\x010\x012\xcc\x03\n" +
	"\x1dResiliencyWithMetadataService\x12^\n" +
	"\x1bUnaryResiliencyWithMetadata\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00\x12j\n" +
	"%ServerStreamingResiliencyWithMetadata\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x000\x01\x12j\n" +
	"%ClientStreamingResiliencyWithMetadata\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00(\x01\x12s\n" +
	",BiDirectionalStreamingResiliencyWithMetadata\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\x00(\x010\x01B;Z9github.com/sisco-exp/my-grpc-proto/protogen/go/resiliencyb\x06proto3"

var (
	file_proto_resiliency_resiliency_proto_rawDescOnce sync.Once
	file_proto_resiliency_resiliency_proto_rawDescData []byte
)

func file_proto_resiliency_resiliency_proto_rawDescGZIP() []byte {
	file_proto_resiliency_resiliency_proto_rawDescOnce.Do(func() {
		file_proto_resiliency_resiliency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resiliency_resiliency_proto_rawDesc), len(file_proto_resiliency_resiliency_proto_rawDesc)))
	})
	return file_proto_resiliency_resiliency_proto_rawDescData
}

var file_proto_resiliency_resiliency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_resiliency_resiliency_proto_goTypes = []any{
	(*ResiliencyRequest)(nil),  // 0: resiliency.ResiliencyRequest
	(*ResiliencyResponse)(nil), // 1: resiliency.ResiliencyResponse
}
var file_proto_resiliency_resiliency_proto_depIdxs = []int32{
	0, // 0: resiliency.ResiliencyService.UnaryResiliency:input_type -> resiliency.ResiliencyRequest
	0, // 1: resiliency.ResiliencyService.ServerStreamingResiliency:input_type -> resiliency.ResiliencyRequest
	0, // 2: resiliency.ResiliencyService.ClientStreamingResiliency:input_type -> resiliency.ResiliencyRequest
	0, // 3: resiliency.ResiliencyService.BiDirectionalStreamingResiliency:input_type -> resiliency.ResiliencyRequest
	0, // 4: resiliency.ResiliencyWithMetadataService.UnaryResiliencyWithMetadata:input_type -> resiliency.ResiliencyRequest
	0, // 5: resiliency.ResiliencyWithMetadataService.ServerStreamingResiliencyWithMetadata:input_type -> resiliency.ResiliencyRequest
	0, // 6: resiliency.ResiliencyWithMetadataService.ClientStreamingResiliencyWithMetadata:input_type -> resiliency.ResiliencyRequest
	0, // 7: resiliency.ResiliencyWithMetadataService.BiDirectionalStreamingResiliencyWithMetadata:input_type -> resiliency.ResiliencyRequest
	1, // 8: resiliency.ResiliencyService.UnaryResiliency:output_type -> resiliency.ResiliencyResponse
	1, // 9: resiliency.ResiliencyService.ServerStreamingResiliency:output_type -> resiliency.ResiliencyResponse
	1, // 10: resiliency.ResiliencyService.ClientStreamingResiliency:output_type -> resiliency.ResiliencyResponse
	1, // 11: resiliency.ResiliencyService.BiDirectionalStreamingResiliency:output_type -> resiliency.ResiliencyResponse
	1, // 12: resiliency.ResiliencyWithMetadataService.UnaryResiliencyWithMetadata:output_type -> resiliency.ResiliencyResponse
	1, // 13: resiliency.ResiliencyWithMetadataService.ServerStreamingResiliencyWithMetadata:output_type -> resiliency.ResiliencyResponse
	1, // 14: resiliency.ResiliencyWithMetadataService.ClientStreamingResiliencyWithMetadata:output_type -> resiliency.ResiliencyResponse
	1, // 15: resiliency.ResiliencyWithMetadataService.BiDirectionalStreamingResiliencyWithMetadata:output_type -> resiliency.ResiliencyResponse
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_resiliency_resiliency_proto_init() }
func file_proto_resiliency_resiliency_proto_init() {
	if File_proto_resiliency_resiliency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resiliency_resiliency_proto_rawDesc), len(file_proto_resiliency_resiliency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_resiliency_resiliency_proto_goTypes,
		DependencyIndexes: file_proto_resiliency_resiliency_proto_depIdxs,
		MessageInfos:      file_proto_resiliency_resiliency_proto_msgTypes,
	}.Build()
	File_proto_resiliency_resiliency_proto = out.File
	file_proto_resiliency_resiliency_proto_goTypes = nil
	file_proto_resiliency_resiliency_proto_depIdxs = nil
}
