// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/resiliency/resiliency.proto

package resiliency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResilincyService_UnaryResilisnecy_FullMethodName                 = "/resiliency.ResilincyService/UnaryResilisnecy"
	ResilincyService_ServerStreamingResiliency_FullMethodName        = "/resiliency.ResilincyService/ServerStreamingResiliency"
	ResilincyService_ClientStreamingResiliency_FullMethodName        = "/resiliency.ResilincyService/ClientStreamingResiliency"
	ResilincyService_BiDirectionalStreamingResiliency_FullMethodName = "/resiliency.ResilincyService/BiDirectionalStreamingResiliency"
)

// ResilincyServiceClient is the client API for ResilincyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResilincyServiceClient interface {
	UnaryResilisnecy(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error)
	ServerStreamingResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResiliencyResponse], error)
	ClientStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResiliencyRequest, ResiliencyResponse], error)
	BiDirectionalStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResiliencyRequest, ResiliencyResponse], error)
}

type resilincyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResilincyServiceClient(cc grpc.ClientConnInterface) ResilincyServiceClient {
	return &resilincyServiceClient{cc}
}

func (c *resilincyServiceClient) UnaryResilisnecy(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiliencyResponse)
	err := c.cc.Invoke(ctx, ResilincyService_UnaryResilisnecy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resilincyServiceClient) ServerStreamingResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResiliencyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResilincyService_ServiceDesc.Streams[0], ResilincyService_ServerStreamingResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResiliencyRequest, ResiliencyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_ServerStreamingResiliencyClient = grpc.ServerStreamingClient[ResiliencyResponse]

func (c *resilincyServiceClient) ClientStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResiliencyRequest, ResiliencyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResilincyService_ServiceDesc.Streams[1], ResilincyService_ClientStreamingResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResiliencyRequest, ResiliencyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_ClientStreamingResiliencyClient = grpc.ClientStreamingClient[ResiliencyRequest, ResiliencyResponse]

func (c *resilincyServiceClient) BiDirectionalStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResiliencyRequest, ResiliencyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResilincyService_ServiceDesc.Streams[2], ResilincyService_BiDirectionalStreamingResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResiliencyRequest, ResiliencyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_BiDirectionalStreamingResiliencyClient = grpc.BidiStreamingClient[ResiliencyRequest, ResiliencyResponse]

// ResilincyServiceServer is the server API for ResilincyService service.
// All implementations must embed UnimplementedResilincyServiceServer
// for forward compatibility.
type ResilincyServiceServer interface {
	UnaryResilisnecy(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error)
	ServerStreamingResiliency(*ResiliencyRequest, grpc.ServerStreamingServer[ResiliencyResponse]) error
	ClientStreamingResiliency(grpc.ClientStreamingServer[ResiliencyRequest, ResiliencyResponse]) error
	BiDirectionalStreamingResiliency(grpc.BidiStreamingServer[ResiliencyRequest, ResiliencyResponse]) error
	mustEmbedUnimplementedResilincyServiceServer()
}

// UnimplementedResilincyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResilincyServiceServer struct{}

func (UnimplementedResilincyServiceServer) UnaryResilisnecy(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryResilisnecy not implemented")
}
func (UnimplementedResilincyServiceServer) ServerStreamingResiliency(*ResiliencyRequest, grpc.ServerStreamingServer[ResiliencyResponse]) error {
	return status.Error(codes.Unimplemented, "method ServerStreamingResiliency not implemented")
}
func (UnimplementedResilincyServiceServer) ClientStreamingResiliency(grpc.ClientStreamingServer[ResiliencyRequest, ResiliencyResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStreamingResiliency not implemented")
}
func (UnimplementedResilincyServiceServer) BiDirectionalStreamingResiliency(grpc.BidiStreamingServer[ResiliencyRequest, ResiliencyResponse]) error {
	return status.Error(codes.Unimplemented, "method BiDirectionalStreamingResiliency not implemented")
}
func (UnimplementedResilincyServiceServer) mustEmbedUnimplementedResilincyServiceServer() {}
func (UnimplementedResilincyServiceServer) testEmbeddedByValue()                          {}

// UnsafeResilincyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResilincyServiceServer will
// result in compilation errors.
type UnsafeResilincyServiceServer interface {
	mustEmbedUnimplementedResilincyServiceServer()
}

func RegisterResilincyServiceServer(s grpc.ServiceRegistrar, srv ResilincyServiceServer) {
	// If the following call panics, it indicates UnimplementedResilincyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResilincyService_ServiceDesc, srv)
}

func _ResilincyService_UnaryResilisnecy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResiliencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResilincyServiceServer).UnaryResilisnecy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResilincyService_UnaryResilisnecy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResilincyServiceServer).UnaryResilisnecy(ctx, req.(*ResiliencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResilincyService_ServerStreamingResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResiliencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResilincyServiceServer).ServerStreamingResiliency(m, &grpc.GenericServerStream[ResiliencyRequest, ResiliencyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_ServerStreamingResiliencyServer = grpc.ServerStreamingServer[ResiliencyResponse]

func _ResilincyService_ClientStreamingResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResilincyServiceServer).ClientStreamingResiliency(&grpc.GenericServerStream[ResiliencyRequest, ResiliencyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_ClientStreamingResiliencyServer = grpc.ClientStreamingServer[ResiliencyRequest, ResiliencyResponse]

func _ResilincyService_BiDirectionalStreamingResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResilincyServiceServer).BiDirectionalStreamingResiliency(&grpc.GenericServerStream[ResiliencyRequest, ResiliencyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilincyService_BiDirectionalStreamingResiliencyServer = grpc.BidiStreamingServer[ResiliencyRequest, ResiliencyResponse]

// ResilincyService_ServiceDesc is the grpc.ServiceDesc for ResilincyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResilincyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resiliency.ResilincyService",
	HandlerType: (*ResilincyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryResilisnecy",
			Handler:    _ResilincyService_UnaryResilisnecy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamingResiliency",
			Handler:       _ResilincyService_ServerStreamingResiliency_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamingResiliency",
			Handler:       _ResilincyService_ClientStreamingResiliency_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalStreamingResiliency",
			Handler:       _ResilincyService_BiDirectionalStreamingResiliency_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/resiliency/resiliency.proto",
}
